### ISSUE TITLE
跳转时  not Found

### ISSUE THREAD

**Issue by wangcc0909** [richardwrq/KRouter#3]
点击跳转到其他module中的activity时,log中打印not Found ,查看相应的module/build/generated/source/kaptKotlin/(buildType)中有map["MainActivity"] = RouteMetadata(RouteType.ACTIVITY, -1, "undefined", "MainActivity", "", "", MainActivity::class.java),
这是什么原因,请告知

**Comment by richardwrq** [comment]
@wangcc0909 你好，你在app中有依赖这个Module吗？这个Module的build.gradle文件也需要加入
`apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: "com.github.richardwrq.krouter"`

**Comment by wangcc0909** [comment]
我所有的module都加了这几个plugin,app中只依赖一个公共的module,集成时会依赖其他的module,还是not Found,

**Comment by richardwrq** [comment]
@wangcc0909 有在Application中调用KRouter.init(context)进行初始化吧？

**Comment by wangcc0909** [comment]
更新到0.1.5可以用了

**Comment by richardwrq** [comment]
感谢你的反馈， 0.1.4版本中对名字包含下划线“_”的Module的命名存在bug，在0.1.5版本中已解决
