### ISSUE TITLE
使用withStringList()传递参数类型为MutableList<String>报错

### ISSUE THREAD

**Issue by wangcc0909** [richardwrq/KRouter#4]
OutgoingActivity_KRouter_Injector.kt: (26, 72): Type mismatch: inferred type is java.util.ArrayList<java.lang.String>? but kotlin.collections.ArrayList<kotlin.String>? /* = java.util.ArrayList<kotlin.String>? */ was expected

使用withStringList和withSerialized方法传递集合时报String的类型不匹配 ,这个问题有好的解决办法吗

**Comment by richardwrq** [comment]
@wangcc0909 
非常高兴收到你的反馈，该问题是在处理kotlin跟java数据类型映射时忽略了存在泛型类的情况导致的，在0.1.8版本已解决该问题，请将版本更新至0.1.8 参考https://github.com/square/kotlinpoet/issues/236
